[package]
name = "audio-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3"
livi = "0.6"
log = "0.4"
lv2_raw = "0.2"
wmidi = "4"
